export const LOAD_TICKER_DATA_INIT = 'LOAD_TICKER_DATA_INIT';
export const LOAD_TICKER_DATA_SUCCESS = 'LOAD_TICKER_DATA_SUCCESS';
export const LOAD_TICKER_DATA_ERROR = 'LOAD_TICKER_DATA_ERROR';

export const LOAD_TRADES_DATA_INIT = 'LOAD_TRADES_DATA_INIT';
export const LOAD_TRADES_DATA_SUCCESS = 'LOAD_TRADES_DATA_SUCCESS';
export const LOAD_TRADES_DATA_ERROR = 'LOAD_TRADES_DATA_ERROR';


export const LOAD_ORDERBOOK_DATA_INIT = 'LOAD_ORDERBOOK_DATA_INIT';
export const LOAD_ORDERBOOK_DATA_SUCCESS = 'LOAD_ORDERBOOK_DATA_SUCCESS';
export const LOAD_ORDERBOOK_DATA_ERROR = 'LOAD_ORDERBOOK_DATA_ERROR';